# Generated by Django 4.2.7 on 2025-08-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_advertisementview'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisementview',
            name='view_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество просмотров'),
        ),
    ]
