# Generated by Django 4.2.7 on 2025-08-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cities',
            field=models.ManyToManyField(blank=True, help_text='Оставьте пустым, чтобы категория была доступна во всех городах', to='ads.city', verbose_name='Города'),
        ),
    ]
