# Generated by Django 4.2.7 on 2025-08-20 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_category_cities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='views_count',
        ),
    ]
