# Generated by Django 4.2.7 on 2025-08-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_remove_views_count_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество просмотров'),
        ),
        migrations.DeleteModel(
            name='AdvertisementView',
        ),
    ]
