# Generated by Django 4.2.7 on 2025-08-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_advertisement_views_count_delete_advertisementview'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('code', models.CharField(max_length=6, verbose_name='Код подтверждения')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Подтвержден')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('expires_at', models.DateTimeField(verbose_name='Дата истечения')),
            ],
            options={
                'verbose_name': 'SMS-верификация',
                'verbose_name_plural': 'SMS-верификации',
                'ordering': ['-created_at'],
            },
        ),
    ]
