# Generated by Django 4.2.7 on 2025-08-21 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ads', '0009_smsverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLastCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('code', models.CharField(max_length=4, verbose_name='Последний код')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='last_sms_code', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Последний код пользователя',
                'verbose_name_plural': 'Последние коды пользователей',
            },
        ),
    ]
